<?php

/**
 * Implements hook_permission().
 */
function task_permission() {
  return array(
    'access all task' => array(
      'title' => t('Access all task'),
    ),
    'access own task' => array(
      'title' => t('Access own task'),
    ),
    'administer task types' => array(
      'title' => t('Administer task types'),
    ),
    'administer tasks' => array(
      'title' => t('Administer tasks'),
    ),
  );
}

/**
 * Loads a task type.
 *
 * @param int $id
 *   The ID of the task type to load.
 *
 * @return \Drupal\task\Entity\TaskType|null
 *   A TaskType object or NULL if the requested $id does not exist.
 */
function task_type_load($id) {
  return entity_load('task_type', $id);
}


/**
 * Implements hook_menu().
 */
function task_menu() {
  $items['admin/structure/task-types'] = array(
    'title' => 'Task types',
    'description' => 'Add and modify task types',
    'route_name' => 'task.task_type_list',
  );
  $items['admin/structure/task-types/add'] = array(
    'title' => 'Add task type',
    'route_name' => 'task.task_type_add',
    'type' => MENU_SIBLING_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/structure/task-types/manage/%task_type'] = array(
    'title' => 'Edit task type',
    'title callback' => 'entity_page_label',
    'title arguments' => array(4),
    'route_name' => 'task.task_type_edit',
  );
  $items['admin/structure/task-types/manage/%task_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/structure/task-types/manage/%task_type/delete'] = array(
    'title' => 'Delete',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'route_name' => 'task.task_type_delete',
  );
  $items['task/add'] = array(
    'title' => 'Add custom task',
    'route_name' => 'task.task_add_page',
  );
  $items['task/add/%task_type'] = array(
    'title' => 'Add task',
    'description' => 'Add task',
    'route_name' => 'task.task_add_form'
  );
  // There has to be a base-item in order for contextual links to work.
  $items['task/%task'] = array(
    'title' => 'Edit',
    'route_name' => 'task.task_edit',
  );
  $items['task/%task/edit'] = array(
    'title' => 'Edit',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );  
  return $items;
}