# Schema for the configuration files of the Task module.

task.type.*:
  type: mapping
  label: 'Task type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    revision:
      type: integer
      label: 'Create new revision'
    description:
      type: text
      label: 'Description'
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Default language'